// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY1NqJcpr-Ttd3gVa-QYfQ3MNc9Bwx9Jg',
    appId: '1:84370637501:web:138556a4fed30558e82dd4',
    messagingSenderId: '84370637501',
    projectId: 'todo-list-98ae1',
    authDomain: 'todo-list-98ae1.firebaseapp.com',
    storageBucket: 'todo-list-98ae1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG38dObL6RMuTUV5vG4jGfmEYNjIXy3Jw',
    appId: '1:84370637501:android:739ea2978609dadbe82dd4',
    messagingSenderId: '84370637501',
    projectId: 'todo-list-98ae1',
    storageBucket: 'todo-list-98ae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdCY0RO5WBFISO7f-ZNlnTU31hyxwOw5w',
    appId: '1:84370637501:ios:94a7bbf783506d79e82dd4',
    messagingSenderId: '84370637501',
    projectId: 'todo-list-98ae1',
    storageBucket: 'todo-list-98ae1.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdCY0RO5WBFISO7f-ZNlnTU31hyxwOw5w',
    appId: '1:84370637501:ios:94a7bbf783506d79e82dd4',
    messagingSenderId: '84370637501',
    projectId: 'todo-list-98ae1',
    storageBucket: 'todo-list-98ae1.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY1NqJcpr-Ttd3gVa-QYfQ3MNc9Bwx9Jg',
    appId: '1:84370637501:web:327283f330cc9e0be82dd4',
    messagingSenderId: '84370637501',
    projectId: 'todo-list-98ae1',
    authDomain: 'todo-list-98ae1.firebaseapp.com',
    storageBucket: 'todo-list-98ae1.appspot.com',
  );
}
